CREATE TABLE HOMEMADE_FOOD(
  ID SERIAL PRIMARY KEY,
  PNAME CHARACTER(40),
	QUANTITY REAL,
  KIND CHARACTER(20),
  ALLERGENS TEXT,
  SELLER CHARACTER(40)
);

--INSERT INTO HOMEMADE_FOOD VALUES (1, 'Gamze Borek', 10, 'Borek', 'Wheat flour', 'Gamze Akyol');
--INSERT INTO HOMEMADE_FOOD VALUES (2, 'Seyma Cookie', 20, 'Cookie', 'Chocolate, Nut, Wheat flour', 'Seymanur Akti');