CREATE TABLE USERS (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(80) NOT NULL,
   SURNAME VARCHAR(80) NOT NULL,
   NICKNAME VARCHAR(80) NOT NULL,
   EMAIL VARCHAR(80) NOT NULL,
   PASSWORD VARCHAR(15) NOT NULL
)
